# Generated by Django 3.0.6 on 2020-06-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('card_id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('access', models.BooleanField(blank=True, default=False)),
                ('registred_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AddField(
            model_name='device',
            name='is_out',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='wait_time',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_ip',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Access')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
            ],
        ),
    ]
