# Generated by Django 3.0.5 on 2020-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200602_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='out_date',
            field=models.DateTimeField(null=True),
        ),
    ]
