# Generated by Django 3.0.4 on 2020-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employees_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
