# Generated by Django 3.0.6 on 2020-05-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('card_id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('access', models.BooleanField(blank=True, default=False)),
                ('registred_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=30, null=True)),
                ('device_model', models.CharField(max_length=30, null=True)),
                ('is_out', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=30, null=True)),
                ('wait_time', models.IntegerField(default=2)),
                ('check_out', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Access')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='status',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_created',
        ),
        migrations.AddField(
            model_name='employees',
            name='advisor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('en', 'en'), ('kz', 'kz'), ('ru', 'ru')], default='en', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='access',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employees'),
        ),
    ]
