# Generated by Django 3.0.6 on 2020-05-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200526_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='student_id',
            new_name='person_id',
        ),
    ]
