# Generated by Django 3.0.6 on 2020-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200526_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
